"""create rag_chat_history table and user_id could be null.

Revision ID: e6f706939079
Revises: 33fa99dff5ec
Create Date: 2025-04-10 18:18:13.664356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6f706939079'
down_revision: Union[str, None] = '33fa99dff5ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Create rag_chat_history table
    op.create_table('rag_chat_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('query', sa.String(), nullable=True),
        sa.Column('response', sa.String(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rag_chat_history_id'), 'rag_chat_history', ['id'], unique=False)

    # Drop old index
    op.drop_index('ix_chat_history_user_id', table_name='chat_history')

    # Use batch mode to alter chat_history and projects tables
    with op.batch_alter_table('chat_history', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.create_index('ix_chat_history_user_id', 'chat_history', ['user_id'], unique=False)
    op.drop_index(op.f('ix_rag_chat_history_id'), table_name='rag_chat_history')
    op.drop_table('rag_chat_history')
    # ### end Alembic commands ###
